Contrast-Security-OSS/agent-operator-images

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.1.17'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.1.18'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.1.19'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.1.2'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.1.20'

src/dotnet-framework/manifest.json
Version: `50.0.19` -> `50.0.21`
=> [OOB] Upgrades 'dotnet-framework' to '50.0.21'

src/dotnet-framework/manifest.json
Version: `50.0.21` -> `50.0.22`
=> [OOB] Upgrades 'dotnet-framework' to '50.0.22'

src/java/manifest.json
Agent: `java`
Version: `4.0.0` -> `4.1.0`
=> [OOB] Upgrades 'java' to '4.1.0'

src/java/manifest.json
Agent: `java`
Version: `4.2.1` -> `4.2.2`
=> [OOB] Upgrades 'java' to '4.2.2'

src/java/manifest.json
Agent: `java`
Version: `4.2.2` -> `4.3.0`
=> [OOB] Upgrades 'java' to '4.3.0'

src/java/manifest.json
Agent: `java`
Version: `4.3.0` -> `4.3.1`
=> [OOB] Upgrades 'java' to '4.3.1'

src/java/manifest.json
Agent: `java`
Version: `4.3.1` -> `4.4.0`
=> [OOB] Upgrades 'java' to '4.4.0'

src/dotnet-framework/manifest.json
Version: `50.0.22` -> `50.0.23`
=> [OOB] Upgrades 'dotnet-framework' to '50.0.23'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.2.0'

src/java/manifest.json
Agent: `java`
Version: `4.4.0` -> `4.5.0`
=> [OOB] Upgrades 'java' to '4.5.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.3.0'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '50.1.1'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.3.1'

src/java/manifest.json
Agent: `java`
Version: `4.5.0` -> `4.5.1`
=> [OOB] Upgrades 'java' to '4.5.1'

src/java/manifest.json
Agent: `java`
Version: `4.5.1` -> `4.6.0`
=> [OOB] Upgrades 'java' to '4.6.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.3.3'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '50.1.3'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '50.1.4'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.3.4'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '50.1.5'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.3.5'

src/java/manifest.json
Agent: `java`
Version: `4.7.0` -> `4.7.1`
=> [OOB] Upgrades 'java' to '4.7.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.26.0'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '50.1.6'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.3.6'

src/java/manifest.json
Agent: `java`
Version: `4.7.1` -> `4.8.0`
=> [OOB] Upgrades 'java' to '4.8.0'

src/php/manifest.json
Agent: `php`
Version: `1.7.0` -> `1.8.0`
=> [OOB] Upgrades 'php' to '1.8.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.27.1'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '50.1.7'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.4.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.27.2'

src/java/manifest.json
Agent: `java`
Version: `4.8.0` -> `4.9.0`
=> [OOB] Upgrades 'java' to '4.9.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.28.0'

src/nodejs-protect/manifest.json
Version: `5.0.0-beta.2` -> `5.0.1`
=> [OOB] Upgrades 'nodejs-protect' to '5.0.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.28.1'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '50.1.8'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '2.4.3'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '50.1.9'

src/java/manifest.json
Agent: `java`
Version: `4.9.0` -> `4.10.0`
=> [OOB] Upgrades 'java' to '4.10.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.29.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.29.1'

src/nodejs-protect/manifest.json
=> [OOB] Upgrades 'nodejs-protect' to '5.1.0'

src/nodejs-protect/manifest.json
=> [OOB] Upgrades 'nodejs-protect' to '5.2.0'

src/dotnet-framework/manifest.json
Version: `50.1.9` -> `50.1.10`
=> [OOB] Upgrades 'dotnet-framework' to '50.1.10'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.30.0'

src/java/manifest.json
Agent: `java`
Version: `4.10.0` -> `4.11.0`
=> [OOB] Upgrades 'java' to '4.11.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.30.1'

src/java/manifest.json
Agent: `java`
Version: `4.11.0` -> `4.11.1`
=> [OOB] Upgrades 'java' to '4.11.1'

src/dotnet-framework/manifest.json
Version: `50.1.10` -> `50.1.11`
=> [OOB] Upgrades 'dotnet-framework' to '50.1.11'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '3.0.0'

src/java/manifest.json
Agent: `java`
Version: `4.11.1` -> `4.12.0`
=> [OOB] Upgrades 'java' to '4.12.0'

src/java/manifest.json
Agent: `java`
Version: `4.12.0` -> `4.12.1`
=> [OOB] Upgrades 'java' to '4.12.1'

src/nodejs-protect/manifest.json
=> [OOB] Upgrades 'nodejs-protect' to '5.3.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.31.0'

src/dotnet-framework/manifest.json
Version: `50.1.11` -> `50.1.12`
=> [OOB] Upgrades 'dotnet-framework' to '50.1.12'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '3.0.1'

src/nodejs-protect/manifest.json
=> [OOB] Upgrades 'nodejs-protect' to '5.4.0'

src/nodejs-protect/manifest.json
=> [OOB] Upgrades 'nodejs-protect' to '5.4.1'

src/java/manifest.json
Agent: `java`
Version: `4.12.1` -> `4.12.2`
=> [OOB] Upgrades 'java' to '4.12.2'

src/nodejs-protect/manifest.json
=> [OOB] Upgrades 'nodejs-protect' to '5.4.2'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.31.1'

src/dotnet-framework/manifest.json
Version: `50.1.12` -> `50.1.13`
=> [OOB] Upgrades 'dotnet-framework' to '50.1.13'

src/php/manifest.json
Agent: `php`
Version: `1.8.0` -> `1.10.0`
=> [OOB] Upgrades 'php' to '1.10.0'

src/java/manifest.json
Agent: `java`
Version: `4.12.2` -> `4.13.0`
=> [OOB] Upgrades 'java' to '4.13.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.31.2'

src/java/manifest.json
Agent: `java`
Version: `4.13.0` -> `4.13.1`
=> [OOB] Upgrades 'java' to '4.13.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.0'

src/dotnet-framework/manifest.json
Version: `50.1.13` -> `50.1.14`
=> [OOB] Upgrades 'dotnet-framework' to '50.1.14'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '3.0.3'

src/dotnet-framework/manifest.json
Version: `50.1.14` -> `51.0.0`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.0.0'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.0.1'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.0.1'

src/java/manifest.json
Agent: `java`
Version: `4.13.1` -> `5.0.0`
=> [OOB] Upgrades 'java' to '5.0.0'

src/php/manifest.json
Agent: `php`
Version: `1.10.0` -> `1.11.0`
=> [OOB] Upgrades 'php' to '1.11.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.2'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.3'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.4'

src/php/manifest.json
Agent: `php`
Version: `1.11.0` -> `1.12.0`
=> [OOB] Upgrades 'php' to '1.12.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.5'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.0.3'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.6'

src/java/manifest.json
Agent: `java`
Version: `5.0.0` -> `5.0.1`
=> [OOB] Upgrades 'java' to '5.0.1'

src/php/manifest.json
Agent: `php`
Version: `1.12.0` -> `1.13.0`
=> [OOB] Upgrades 'php' to '1.13.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.7'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.0.4'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.32.8'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.0.5'

src/java/manifest.json
Agent: `java`
Version: `5.0.2` -> `5.1.0`
=> [OOB] Upgrades 'java' to '5.1.0'

src/php/manifest.json
Agent: `php`
Version: `1.14.0` -> `1.15.0`
=> [OOB] Upgrades 'php' to '1.15.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.0.6'

src/nodejs/manifest.json
Version: `4.32.9` -> `4.32.10`
=> [OOB] Upgrades 'nodejs' to '4.32.10'

src/nodejs/manifest.json
Version: `4.32.10` -> `4.32.11`
=> [OOB] Upgrades 'nodejs' to '4.32.11'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.0.7'

src/java/manifest.json
Agent: `java`
Version: `5.1.0` -> `5.1.1`
=> [OOB] Upgrades 'java' to '5.1.1'

src/nodejs/manifest.json
Version: `4.32.11` -> `4.32.12`
=> [OOB] Upgrades 'nodejs' to '4.32.12'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.0.8'

src/java/manifest.json
Agent: `java`
Version: `5.1.1` -> `5.1.2`
=> [OOB] Upgrades 'java' to '5.1.2'

src/php/manifest.json
Agent: `php`
Version: `1.15.0` -> `1.16.0`
=> [OOB] Upgrades 'php' to '1.16.0'

src/nodejs/manifest.json
Version: `4.32.12` -> `4.32.13`
=> [OOB] Upgrades 'nodejs' to '4.32.13'

src/nodejs/manifest.json
Version: `4.32.13` -> `4.32.14`
=> [OOB] Upgrades 'nodejs' to '4.32.14'

src/nodejs/manifest.json
Version: `4.32.14` -> `4.32.15`
=> [OOB] Upgrades 'nodejs' to '4.32.15'

src/java/manifest.json
Agent: `java`
Version: `5.1.2` -> `5.1.3`
=> [OOB] Upgrades 'java' to '5.1.3'

src/php/manifest.json
Agent: `php`
Version: `1.16.0` -> `1.17.0`
=> [OOB] Upgrades 'php' to '1.17.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.1.0'

src/dotnet-framework/manifest.json
Version: `51.0.8` -> `51.0.10`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.10'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.1.1'

.github/workflows/build.yml, .github/workflows/oob-update.yaml, src/dotnet-core/manifest.json, src/java/manifest.json, src/nodejs-protect/manifest.json, src/nodejs/manifest.json
* Publish arm64 images for java, dotnet-core, nodejs, nodejs-protect
* Replace deprecated github action for automerge with github cli
=> DOTNET-5162 Publish arm64 versions

src/java/manifest.json
Agent: `java`
Version: `5.2.0` -> `5.2.1`
=> [OOB] Upgrades 'java' to '5.2.1'

src/java/manifest.json
Agent: `java`
Version: `5.2.1` -> `5.2.2`
=> [OOB] Upgrades 'java' to '5.2.2'

src/nodejs/manifest.json
Version: `4.32.16` -> `4.32.17`
=> [OOB] Upgrades 'nodejs' to '4.32.17'

src/nodejs/manifest.json
Version: `4.32.17` -> `4.32.18`
=> [OOB] Upgrades 'nodejs' to '4.32.18'

src/php/manifest.json
Agent: `php`
Version: `1.17.0` -> `1.18.0`
=> [OOB] Upgrades 'php' to '1.18.0'

src/nodejs/manifest.json
Version: `4.32.18` -> `4.32.19`
=> [OOB] Upgrades 'nodejs' to '4.32.19'

src/php/manifest.json
Agent: `php`
Version: `1.18.0` -> `1.18.1`
=> [OOB] Upgrades 'php' to '1.18.1'

src/php/manifest.json
Agent: `php`
Version: `1.18.1` -> `1.19.0`
=> [OOB] Upgrades 'php' to '1.19.0'

src/java/manifest.json
Agent: `java`
Version: `5.2.2` -> `5.2.3`
=> [OOB] Upgrades 'java' to '5.2.3'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.1.2'

src/dotnet-framework/manifest.json
Version: `51.0.10` -> `51.0.12`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.12'

src/nodejs/manifest.json
Version: `4.32.19` -> `4.32.20`
=> [OOB] Upgrades 'nodejs' to '4.32.20'

src/nodejs/manifest.json
Version: `4.32.20` -> `4.33.0`
=> [OOB] Upgrades 'nodejs' to '4.33.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.1.4'

src/java/manifest.json
Agent: `java`
Version: `5.2.3` -> `5.3.0`
=> [OOB] Upgrades 'java' to '5.3.0'

src/java/manifest.json
Agent: `java`
Version: `5.3.0` -> `5.3.1`
=> [OOB] Upgrades 'java' to '5.3.1'

src/java/manifest.json
Agent: `java`
Version: `5.3.1` -> `5.4.0`
=> [OOB] Upgrades 'java' to '5.4.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.33.1'

src/php/manifest.json
Agent: `php`
Version: `1.19.0` -> `1.20.1`
=> [OOB] Upgrades 'php' to '1.20.1'

src/dotnet-framework/manifest.json
Version: `51.0.12` -> `51.0.15`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.15'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.1.6'

src/php/manifest.json
Agent: `php`
Version: `1.20.1` -> `1.21.0`
=> [OOB] Upgrades 'php' to '1.21.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.33.2'

src/java/manifest.json
Agent: `java`
Version: `5.4.0` -> `5.4.1`
=> [OOB] Upgrades 'java' to '5.4.1'

src/java/manifest.json
Agent: `java`
Version: `5.4.1` -> `6.0.0`
=> [OOB] Upgrades 'java' to '6.0.0'

src/php/manifest.json
Agent: `php`
Version: `1.21.0` -> `1.22.0`
=> [OOB] Upgrades 'php' to '1.22.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.33.3'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.34.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.35.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.36.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.36.1'

src/php/manifest.json
Agent: `php`
Version: `1.22.0` -> `1.23.0`
=> [OOB] Upgrades 'php' to '1.23.0'

src/java/manifest.json
Agent: `java`
Version: `6.0.0` -> `6.1.0`
=> [OOB] Upgrades 'java' to '6.1.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.2'

src/dotnet-framework/manifest.json
Version: `51.0.18` -> `51.0.20`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.20'

src/dotnet-framework/manifest.json
Version: `51.0.20` -> `51.0.21`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.21'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.3'

src/java/manifest.json
Agent: `java`
Version: `6.1.0` -> `6.1.1`
=> [OOB] Upgrades 'java' to '6.1.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.36.2'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '4.37.0'

src/dotnet-framework/manifest.json
Version: `51.0.21` -> `51.0.22`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.22'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.4'

src/php/manifest.json
Agent: `php`
Version: `1.23.0` -> `1.24.0`
=> [OOB] Upgrades 'php' to '1.24.0'

src/php/manifest.json
Agent: `php`
Version: `1.24.0` -> `1.24.1`
=> [OOB] Upgrades 'php' to '1.24.1'

.github/CODEOWNERS, .github/workflows/build.yml, .github/workflows/oob-update.yaml, README.md, src/python/Dockerfile, src/python/manifest.json
Working for python versions 3.8-3.12 but we can't support alpine due to filename collisions with one of the c extensions.
Python wheels would have made this easier (instead we make a builder for each python version and merge all of them together)
=> DOTNET-5305 Add python init container

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.5'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.6'

src/dotnet-framework/manifest.json
Version: `51.0.22` -> `51.0.24`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.24'

src/java/manifest.json
Agent: `java`
Version: `6.2.0` -> `6.2.1`
=> [OOB] Upgrades 'java' to '6.2.1'

src/php/manifest.json
Agent: `php`
Version: `1.24.1` -> `1.25.0`
=> [OOB] Upgrades 'php' to '1.25.0'

src/php/manifest.json
Agent: `php`
Version: `1.25.0` -> `1.26.0`
=> [OOB] Upgrades 'php' to '1.26.0'

src/dotnet-framework/manifest.json
Version: `51.0.24` -> `51.0.26`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.26'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.8'

src/python/manifest.json
A pipeline issue prevented the automated upgrade.
It should be fixed in https://github.com/Contrast-Security-Inc/python-agent/pull/1952
We've also made https://github.com/Contrast-Security-Inc/python-agent/pull/1953 to reduce the dependencies of this operator update step, which should make future failures less likely.
=> manually upgrade python version to 7.4.0

src/php/manifest.json
Agent: `php`
Version: `1.26.0` -> `1.26.1`
=> [OOB] Upgrades 'php' to '1.26.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.4.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.4.2'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.4.3'

src/java/manifest.json
Agent: `java`
Version: `6.3.1` -> `6.3.2`
=> [OOB] Upgrades 'java' to '6.3.2'

src/nodejs/Dockerfile
SWC library has changed and only installs the native components for the OS it was installed on (so we are missing alpine bits because we install on bookworm). Pinning to this version (and alpine) is a workaround for now.
=> Pin node version

src/nodejs/Dockerfile
=> Install both musl and glibc versions of swc/core for the NodeJS agent

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.4.4'

src/php/manifest.json
Agent: `php`
Version: `1.26.1` -> `1.26.2`
=> [OOB] Upgrades 'php' to '1.26.2'

src/java/manifest.json
Agent: `java`
Version: `6.3.2` -> `6.3.3`
=> [OOB] Upgrades 'java' to '6.3.3'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.11'

src/dotnet-framework/manifest.json
Version: `51.0.28` -> `51.0.29`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.29'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.5.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.6.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '8.0.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.12'

src/dotnet-framework/manifest.json
Version: `51.0.29` -> `51.0.30`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.30'

src/java/manifest.json
Agent: `java`
Version: `6.3.3` -> `6.4.0`
=> [OOB] Upgrades 'java' to '6.4.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.13'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.6.1'

src/java/manifest.json
Agent: `java`
Version: `6.4.0` -> `6.4.1`
=> [OOB] Upgrades 'java' to '6.4.1'

src/dotnet-framework/manifest.json
Version: `51.0.30` -> `51.0.32`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.32'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.14'

src/php/manifest.json
Agent: `php`
Version: `1.27.0` -> `1.28.0`
=> [OOB] Upgrades 'php' to '1.28.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '8.1.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.6.2'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.15'

src/dotnet-framework/manifest.json
Version: `51.0.32` -> `51.0.33`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.33'

src/php/manifest.json
Agent: `php`
Version: `1.28.0` -> `1.28.1`
=> [OOB] Upgrades 'php' to '1.28.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.7.0'

src/java/manifest.json
Agent: `java`
Version: `6.4.1` -> `6.5.0`
=> [OOB] Upgrades 'java' to '6.5.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.7.1'

src/java/manifest.json
Agent: `java`
Version: `6.5.0` -> `6.5.1`
=> [OOB] Upgrades 'java' to '6.5.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.7.3'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.16'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.7.4'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.7.5'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '8.3.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.8.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '8.4.0'

src/java/manifest.json
Agent: `java`
Version: `6.5.1` -> `6.5.2`
=> [OOB] Upgrades 'java' to '6.5.2'

src/php/manifest.json
Agent: `php`
Version: `1.28.1` -> `1.30.0`
=> [OOB] Upgrades 'php' to '1.30.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.9.0'

src/java/manifest.json
Agent: `java`
Version: `6.5.2` -> `6.5.3`
=> [OOB] Upgrades 'java' to '6.5.3'

src/php/manifest.json
Agent: `php`
Version: `1.30.0` -> `1.31.0`
=> [OOB] Upgrades 'php' to '1.31.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.10.1'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.17'

src/dotnet-framework/manifest.json
Version: `51.0.34` -> `51.0.35`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.35'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.18'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.10.2'

src/java/manifest.json
Agent: `java`
Version: `6.5.3` -> `6.5.4`
=> [OOB] Upgrades 'java' to '6.5.4'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.11.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '8.5.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.12.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.19'

src/dotnet-framework/manifest.json
Version: `51.0.36` -> `51.0.37`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.37'

src/java/manifest.json
Agent: `java`
Version: `6.5.4` -> `6.6.0`
=> [OOB] Upgrades 'java' to '6.6.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.12.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.13.0'

src/java/manifest.json
Agent: `java`
Version: `6.6.0` -> `6.7.0`
=> [OOB] Upgrades 'java' to '6.7.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.20'

src/dotnet-framework/manifest.json
Version: `51.0.37` -> `51.0.38`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.38'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '8.6.0'

src/php/manifest.json
Agent: `php`
Version: `1.31.0` -> `1.33.0`
=> [OOB] Upgrades 'php' to '1.33.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '9.0.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.21'

src/java/manifest.json
Agent: `java`
Version: `6.7.0` -> `6.8.0`
=> [OOB] Upgrades 'java' to '6.8.0'

src/java/manifest.json
Agent: `java`
Version: `6.8.0` -> `6.9.0`
=> [OOB] Upgrades 'java' to '6.9.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.22'

src/dotnet-framework/manifest.json
Version: `51.0.39` -> `51.0.40`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.40'

src/php/manifest.json
Agent: `php`
Version: `1.33.0` -> `1.34.0`
=> [OOB] Upgrades 'php' to '1.34.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '9.1.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.23'

src/dotnet-framework/manifest.json
Version: `51.0.40` -> `51.0.41`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.41'

src/java/manifest.json
Agent: `java`
Version: `6.9.0` -> `6.10.0`
=> [OOB] Upgrades 'java' to '6.10.0'

src/java/manifest.json
Agent: `java`
Version: `6.10.0` -> `6.10.1`
=> [OOB] Upgrades 'java' to '6.10.1'

src/php/manifest.json
Agent: `php`
Version: `1.34.0` -> `1.35.0`
=> [OOB] Upgrades 'php' to '1.35.0'

src/java/manifest.json
Agent: `java`
Version: `6.10.1` -> `6.10.2`
=> [OOB] Upgrades 'java' to '6.10.2'

src/dotnet-framework/manifest.json
Version: `51.0.41` -> `51.0.42`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.42'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.25'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '9.2.0'

src/java/manifest.json
Agent: `java`
Version: `6.10.2` -> `6.11.0`
=> [OOB] Upgrades 'java' to '6.11.0'

src/java/manifest.json
Agent: `java`
Version: `6.11.0` -> `6.11.1`
=> [OOB] Upgrades 'java' to '6.11.1'

src/dotnet-framework/manifest.json
Version: `51.0.42` -> `51.0.43`
=> [OOB] Upgrades 'dotnet-framework' to '51.0.43'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.2.26'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '9.4.0'

src/java/manifest.json
Agent: `java`
Version: `6.11.1` -> `6.12.0`
=> [OOB] Upgrades 'java' to '6.12.0'

src/dotnet-framework/manifest.json
Version: `51.0.43` -> `51.1.0`
=> [OOB] Upgrades 'dotnet-framework' to '51.1.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.0'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.1.1'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.1'

src/java/manifest.json
Agent: `java`
Version: `6.12.0` -> `6.12.1`
=> [OOB] Upgrades 'java' to '6.12.1'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.2'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.1.2'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '9.5.1'

src/php/manifest.json
Agent: `php`
Version: `1.35.0` -> `1.36.0`
=> [OOB] Upgrades 'php' to '1.36.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '9.6.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.3'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.1.3'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '9.7.0'

src/java/manifest.json
Agent: `java`
Version: `6.12.1` -> `6.13.0`
=> [OOB] Upgrades 'java' to '6.13.0'

src/nodejs/manifest.json
Automated OOB update requested by tough-griff.
Version: `5.13.0` -> `5.22.0`
=> [OOB] Upgrades 'nodejs' to '5.22.0'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.1.4'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.4'

src/php/manifest.json
Agent: `php`
Version: `1.36.0` -> `1.37.0`
=> [OOB] Upgrades 'php' to '1.37.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.6'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.24.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '9.8.0'

src/php/manifest.json
Agent: `php`
Version: `1.37.0` -> `1.38.0`
=> [OOB] Upgrades 'php' to '1.38.0'

src/python/Dockerfile
Not sure if this is the right order of operations, but the python agent team is dropping support for python version 3.8 in the next release.
Should this PR go through first, and then we release the agent, or the other way around?
=> PYT-3680 Remove build for python 3.8

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.1.7'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.7'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.25.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.0.0'

src/java/manifest.json
Agent: `java`
Version: `6.13.0` -> `6.14.0`
=> [OOB] Upgrades 'java' to '6.14.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.26.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.0.2'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.27.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.1.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.8'

src/python/Dockerfile, src/python/fetch-python.sh
The Python agent has started distributing prebuilt wheels in v10.0.0 . This change updates the build to use those wheels. Some advantages of wheels include
* no longer needing a separate build stage for each supported Python version
* easier reproducibility, since we're downloading prebuilt packages instead of building them in a slim-bookworm image.
* now supporting Alpine and other musllibc environments! (with libgcc available at runtime for linking)
This script may appear overly complex. It's generalized so that it can be used by other Contrast installation tools with minimal changes.
=> PYT-3173: download wheels for the Python agent

src/nodejs/Dockerfile
1.3.39 is old--we require 1.5.29 now
=> NODE-3727 Let npm determine the correct @swc/core version

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.1.8'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.27.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.27.2'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.28.0'

src/php/manifest.json
Agent: `php`
Version: `1.38.0` -> `1.39.0`
=> [OOB] Upgrades 'php' to '1.39.0'

src/java/manifest.json
Agent: `java`
Version: `6.14.0` -> `6.15.0`
=> [OOB] Upgrades 'java' to '6.15.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.29.0'

src/python/fetch-python.sh
There's an issue with python in the operator currently. Description approximately copied from [slack](https://contrastsecurityinc.slack.com/archives/CFD8WK17X/p1741040741907349?thread_ts=1741012578.142949&cid=CFD8WK17X):
---
For python, the operator comes bundled with every possible binary we might need at runtime (all supported python versions + platforms). The problem is that in python 3.10 and earlier, C extension .so files built for musl and glibc have the same filename (this was identified as a [bug in cpython](https://github.com/python/cpython/issues/87278)). When we added musl support to the operator we started accidentally overwriting the glibc builds for 3.9 and 3.10 with musl builds.
We're going to be able to fix the build so that the operator works again for all supported …
=> bugfix: skip musl download for python 3.9 and 3.10

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.2.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.10'

src/dotnet-framework/manifest.json
Version: `51.1.9` -> `51.1.10`
=> [OOB] Upgrades 'dotnet-framework' to '51.1.10'

src/dotnet-core/Dockerfile
Copy the ContrastChainLoader based on arch  to the /runtimes/linux/native folder
This is blocked until the next release of the dotnet-agent with a fix for the ContrastChainLoader looking for the correct ContrastProfiler.so
=> AO-68 Copy the ContrastChainLoader based on arch 

src/java/manifest.json
Agent: `java`
Version: `6.15.0` -> `6.15.1`
=> [OOB] Upgrades 'java' to '6.15.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.30.0'

src/java/manifest.json
Agent: `java`
Version: `6.15.1` -> `6.15.2`
=> [OOB] Upgrades 'java' to '6.15.2'

src/java/manifest.json
Agent: `java`
Version: `6.15.2` -> `6.15.3`
=> [OOB] Upgrades 'java' to '6.15.3'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.3.0'

src/java/manifest.json
Agent: `java`
Version: `6.15.3` -> `6.16.0`
=> [OOB] Upgrades 'java' to '6.16.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.11'

src/dotnet-framework/manifest.json
Version: `51.1.10` -> `51.1.11`
=> [OOB] Upgrades 'dotnet-framework' to '51.1.11'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.31.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.32.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.12'

src/dotnet-framework/manifest.json
Version: `51.1.11` -> `51.1.12`
=> [OOB] Upgrades 'dotnet-framework' to '51.1.12'

src/php/manifest.json
Agent: `php`
Version: `1.39.0` -> `1.40.0`
=> [OOB] Upgrades 'php' to '1.40.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.33.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.4.0'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.13'

src/dotnet-framework/manifest.json
Version: `51.1.12` -> `51.1.13`
=> [OOB] Upgrades 'dotnet-framework' to '51.1.13'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.34.0'

src/dotnet-framework/manifest.json
Version: `51.1.13` -> `51.1.14`
=> [OOB] Upgrades 'dotnet-framework' to '51.1.14'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.3.14'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.5.0'

src/php/manifest.json
Agent: `php`
Version: `1.40.0` -> `1.41.0`
=> [OOB] Upgrades 'php' to '1.41.0'

src/python/Dockerfile, src/python/fetch-python.sh
pip 25.1 includes a [new --json flag](https://pip.pypa.io/en/stable/news/#:~:text=Add%20a%20structured%20%2D%2Djson%20output%20to%20pip%20index%20versions) for structured output, which should be stable for automated use like fetch-python.sh. This PR switches to using this output. I
=> python: use json output to get latest version

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.6.1'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.35.1'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.4.0'

src/dotnet-framework/manifest.json
Version: `51.1.14` -> `51.2.0`
=> [OOB] Upgrades 'dotnet-framework' to '51.2.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.7.0'

src/java/manifest.json
Agent: `java`
Version: `6.16.0` -> `6.17.0`
=> [OOB] Upgrades 'java' to '6.17.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.36.0'

src/php/manifest.json
Agent: `php`
Version: `1.41.0` -> `1.42.0`
=> [OOB] Upgrades 'php' to '1.42.0'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.37.0'

src/python/manifest.json
=> [OOB] Upgrades 'python' to '10.9.0'

src/dotnet-core/Dockerfile, src/dotnet-framework/Dockerfile
NuGet can take a bit of time from pushing up the package to when it is available for download. This adds curl retries to help reduce the docker build step from failing on new releases.
=> AO-62 Add curl retry for NuGet pulls

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.38.0'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.2.3'

src/nodejs/manifest.json
=> [OOB] Upgrades 'nodejs' to '5.39.1'

src/flex/Dockerfile, src/flex/manifest.json
:sparkles: update service flags for parent directory style
With the 0.8.0 version of the Flex Agent and [CFA-222](https://contrast.atlassian.net/browse/CFA-222), the Flex Agent now expects `--comms-dir` and `--agents-dir` to be `--comms-parent-dir` and `--agents-parent-dir` with values pointing to the directories that house the `flex-comms` and `flex-agents` directory respectively. This was done so that the Flex Agent has a lower level directory to create and control in case users specify directories like `/usr/bin`, which we don't want to modify and take ownership of.
[CFA-222]: https://contrast.atlassian.net/browse/CFA-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CFA-229 Flex Agent Parent Directory Configuration

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.2.5'

src/dotnet-core/manifest.json
=> [OOB] Upgrades 'dotnet-core' to '4.5.0'

src/php/manifest.json
Agent: `php`
Version: `1.43.0` -> `1.44.0`
=> [OOB] Upgrades 'php' to '1.44.0'

src/flex/manifest.json
Agent: `flex`
Version: `1.2.0` -> `1.2.1`
=> [OOB] Upgrades 'flex' to '1.2.1'

src/flex/manifest.json
Agent: `flex`
Version: `1.2.1` -> `1.2.2`
=> [OOB] Upgrades 'flex' to '1.2.2'

src/python/manifest.json
Version: `10.12.0` -> `10.13.1`
=> [OOB] Upgrades 'python' to '10.13.1'

src/dotnet-framework/manifest.json
=> [OOB] Upgrades 'dotnet-framework' to '51.3.1'

src/php/manifest.json
Agent: `php`
Version: `1.44.0` -> `1.45.0`
=> [OOB] Upgrades 'php' to '1.45.0'

src/flex/manifest.json
Agent: `flex`
Version: `1.2.2` -> `1.3.0`
=> [OOB] Upgrades 'flex' to '1.3.0'

src/python/manifest.json
Version: `10.14.0` -> `10.15.1`
=> [OOB] Upgrades 'python' to '10.15.1'

src/flex/Dockerfile
- find all versions of the PHP `contrast.ini` file and update the path to use the environment `CONTRAST_MOUNT_PATH`
- the command should allow for any PHP agent version number
- the command should allow for any architecture
- if no files are changed, the build should fail
contrast.ini (before)
```
extension=/usr/bin/contrast-flex-agent/flex-agents/php/1.44.0/amd64/contrast.so
```
contrast.ini (after)
```
extension=${CONTRAST_MOUNT_PATH}/flex-agents/php/1.44.0/amd64/contrast.so
```
=> CFA-283 - Update PHP agent ini paths in Dockerfile

src/php/manifest.json
Agent: `php`
Version: `1.45.0` -> `1.46.0`
=> [OOB] Upgrades 'php' to '1.46.0'

src/java/manifest.json
Agent: `java`
Version: `6.20.1` -> `6.21.0`
=> [OOB] Upgrades 'java' to '6.21.0'
